name: CI
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [backend, frontend]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd ${{ matrix.folder }}
          npm install
      - name: Run tests
        run: |
          cd ${{ matrix.folder }}
          npm test
